SELECT * FROM "MEMBER";
	

<-- 비밀번호 암호화 -->
UPDATE "MEMBER" SET
MEMBER_PW = '$2a$10$ZzONlW.LO2gXDNymEcCjVu1SLzzEsdnCstAC66nQIIbvSwtdAc/J.';


SELECT COUNT(*) FROM "MEMBER"
WHERE MEMBER_EMAIL = 'one@kosaran'
AND MEMBER_STATUS = '0';

SELECT COUNT(*) FROM "MEMBER"
WHERE MEMBER_EMAIL = 'one@kosaran'
AND MEMBER_STATUS = '0';

SELECT * FROM "GROUP";
SELECT * FROM "GROUP_TOPIC";
SELECT * FROM "MEMBER_JOIN";
SELECT * FROM "SAMPLE";

UPDATE "MEMBER" SET MEMBER_EMAIL = 'six@kosaran',
MEMBER_NAME = '여섯육'
WHERE MEMBER_NO = 6;

SELECT MEMBER_EMAIL FROM MEMBER
WHERE MEMBER_EMAIL = 'khbond6789@gmail.com'
AND MEMBER_NAME = '보온드'
AND MEMBER_TEL = '01012345678';
