SELECT * FROM "MEMBER";
SELECT * FROM "MEMBER_IMG";
SELECT * FROM "GROUP";
SELECT * FROM GROUP_IMG;
SELECT * FROM POST;
	

<-- 비밀번호 암호화 -->
UPDATE "MEMBER" SET
MEMBER_PW = '$2a$10$ZzONlW.LO2gXDNymEcCjVu1SLzzEsdnCstAC66nQIIbvSwtdAc/J.';


SELECT COUNT(*) FROM "MEMBER"
WHERE MEMBER_EMAIL = 'one@kosaran'
AND MEMBER_STATUS = '0';

SELECT COUNT(*) FROM "MEMBER"
WHERE MEMBER_EMAIL = 'one@kosaran'
AND MEMBER_STATUS = '0';

SELECT * FROM "GROUP";
SELECT * FROM "GROUP_TOPIC";
SELECT * FROM "MEMBER_JOIN";
SELECT * FROM "SAMPLE";

UPDATE "MEMBER" SET MEMBER_EMAIL = 'six@kosaran',
MEMBER_NAME = '여섯육'
WHERE MEMBER_NO = 6;

SELECT MEMBER_EMAIL FROM MEMBER
WHERE MEMBER_EMAIL = 'khbond6789@gmail.com'
AND MEMBER_NAME = '보온드'
AND MEMBER_TEL = '01012345678';

UPDATE MEMBER SET
MEMBER_STATUS = '0'
WHERE MEMBER_NO = 2;

UPDATE GROUP_IMG SET
GROUP_IMG_ORIGIN = '분노의 짱구'
WHERE GROUP_NO = 19;

COMMIT;

SELECT * FROM MEMBER_IMG
WHERE MEMBER_NO = 5;

		SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NAME, MEMBER_BIRTH, MEMBER_TEL, 
		SIGNUP_DATE, AUTHORITY,
		(SELECT MEMBER_IMG_PATH||MEMBER_IMG_RENAME FROM "MEMBER_IMG" MI WHERE MI.MEMBER_NO = M.MEMBER_NO) PROFILE_IMG
		FROM "MEMBER" M
		WHERE MEMBER_STATUS != '2'
		AND MEMBER_EMAIL = 'one@kosaran';
		
	

SELECT * FROM "MEMBER_JOIN";

SELECT MJ.MEMBER_NO, (SELECT MEMBER_NAME FROM "MEMBER" M WHERE MJ.MEMBER_NO = M.MEMBER_NO)MEMBER_NAME, 
	LEADER_YN, GROUP_NO
FROM "MEMBER_JOIN" MJ
WHERE GROUP_NO = 16
AND JOIN_STATUS = 0;